# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "pixelcraft"
client_id = "fa8118a7a881911df813e0751fd5b9f6"
application_url = "https://support-prevention-stories-ensure.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://support-prevention-stories-ensure.trycloudflare.com/auth/callback",
  "https://support-prevention-stories-ensure.trycloudflare.com/auth/shopify/callback",
  "https://support-prevention-stories-ensure.trycloudflare.com/api/auth/callback",
  "https://support-prevention-stories-ensure.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "pixelcraft-creations.myshopify.com"
